@startuml LoginAD
start
repeat
    :Ввод электронной почты;
    :Ввод пароля;
    if (Проверка учетных данных) then (успех)
        :Перенаправление на главную страницу;
        stop
    else (неудача)
        :Ошибка: Неверный email или пароль;
    endif
repeat while (Попробовать снова?)
@enduml