@startuml PasswordRecovery
start

repeat
    :Ввод электронной почты;
    if (Аккаунт с такой почтой существует?) then (да)
        :Генерация уникальной ссылки для восстановления пароля;
        :Отправка ссылки на электронную почту;
        :Уведомление пользователя об отправке ссылки;
        stop
    else (нет)
        :Ошибка: Аккаунт с такой почтой не найден;
    endif
repeat while (Попробовать снова?)
