@startuml RegAD
start
repeat
    :Ввод электронной почты;
    :Ввод имени;
    :Ввод фамилии;
    :Ввод пароля;
    :Создание профиля;
    if (Аккаунт с такой почтой уже существует?) then (нет)
        :Генерация уникальной ссылки для подтверждения регистрации;
        :Отправка ссылки на электронную почту;
        :Уведомление пользователя об отправке ссылки;
        stop
    else (да)
        :Ошибка: На такой email уже зарегистрирован другой аккаунт;
    endif
repeat while (Попробовать снова?)
@enduml