@startuml ViewProjectStatistics
start

:Открытие страницы статистики проекта;
:Просмотр статистики проекта за текущую неделю;

if (Хотите применить фильтры?) then (да)
    :Выбор категорий для фильтрации;
    :Выбор периода времени для фильтрации;

    :Применение фильтров;
    :Просмотр отфильтрованной статистики;
else (нет)
    :Продолжение просмотра стандартной статистики без фильтров;
endif

:Возврат на страницу проекта;
stop
@enduml