@startuml ManageUsersAD
start

:Открытие страницы управления проектом;
:Выбор действия ("Редактировать роль" или "Удалить пользователя");

if (Выбрано действие "Редактировать роль пользователя"?) then (да)
    :Выбор пользователя из списка участников проекта;
    :Выбор новой роли (Менеджер или Сотрудник);

    if (Сохранить изменения?) then (да)
        :Обновление роли пользователя в базе данных;
        :Уведомление об успешном изменении роли;
    else (нет)
        :Отмена редактирования роли;
    endif

elseif (Выбрано действие "Удалить пользователя"?) then (да)
    :Выбор пользователя из списка участников проекта;

    if (Подтверждение удаления?) then (да)
        :Удаление пользователя из проекта;
        :Уведомление об успешном удалении пользователя;
    else (нет)
        :Отмена удаления пользователя;
    endif
else if (Выбрано действие "Настроить категории пользователя"?) then (да)
    :Выбор пользователя из списка участников проекта;
    :Выбор необходимых категорий пользователю;

    if (Сохранить изменения?) then (да)
        :Обновление категорий пользователя в базе данных;
        :Уведомление об успешном изменении категорий;
    else (нет)
        :Отмена редактирования категорий;
    endif    

else (нет)
    :Просмотр списка участников без изменений;
endif

:Возврат на страницу проекта;
stop
@enduml