@startuml ViewLog
start

:Открытие страницы лога проекта;
:Просмотр истории действий проекта;

if (Хотите сохранить лог?) then (да)
    :Начало процесса сохранения лога;

    if (Сохранение успешно?) then (да)
        :Уведомление о успешном сохранении лога;
    else (нет)
        :Уведомление о неудаче при сохранении лога;
    endif

else (нет)
    :Продолжение просмотра лога без сохранения;
endif

:Возврат на страницу проекта;
stop
@enduml