@startuml usecaseDiagram
left to right direction

actor Мереджер as Manager
actor Админ as Admin
actor Сотрудник as Employee
package "Система управления проектами" {
    rectangle "Работать с пользователями" {
        usecase "Регистрация" as RegUC
        usecase "Авторизация" as AuthUC
        usecase "Восстановление пароля" as RecoveryUC

        usecase "Редактировать профиль" as UserUC
            usecase "Сбросить пароль" as PassUC
            usecase "Изменить имя" as NameUC
    }

    rectangle "Работа с проектами" {
        usecase "Работать с проектами" as ProjectUC
            usecase "Создать проект" as ProjectCreateUC
            usecase "Изменить проект" as ProjectEditUC
            usecase "Удалить проект" as ProjectDeleteUC
    }
    rectangle "Работа с категориями" {
        usecase "Работать с катeгориями" as СategoryUC
            usecase "Создать катeгорию" as СategoryCreateUC
            usecase "Изменить катeгорию" as СategoryEditUC
            usecase "Удалить катeгорию" as СategoryDeleteUC
    }

    rectangle "Работа с задачами" {
        usecase "Работать с задачами" as TaskUC
            usecase "Добавить задачу" as TaskCreateUC
            usecase "Редактировать задачу" as TaskEditUC
            usecase "Удалить задачу" as TaskDeletetUC
            usecase "Восстановить задачу" as TaskRestoreUC
            usecase "Переместить задачу" as TaskMoveUC
    }

    rectangle "Совместная работа" {
        usecase "Совместная работа" as СollaborationUC
            usecase "Пригласить пользователя на доску" as InviteUC
            usecase "Удалить пользователя из проекта" as RemoveUC
            usecase "Редактировать роль" as UpdateUC
            usecase "Назначать категории" as UserCategoryUC
    }

     rectangle "Лог и статистика" {
            usecase "Просмотр лога" as LogUC
            usecase "Сохранение лога" as SaveLogUC
            usecase "Просмотр статистики" as StatisticsUC
    }


Admin .|> Manager
Manager .|> Employee

Employee -- RegUC
Employee -- AuthUC
Employee -- UserUC
Employee -- RecoveryUC

    UserUC ..> PassUC: "include"
    UserUC ..> NameUC: "include"

Manager -- СategoryUC
    СategoryUC ..> СategoryCreateUC: "include"
    СategoryUC ..> СategoryEditUC: "include"
    СategoryUC ..> СategoryDeleteUC: "include"

Employee -- TaskUC
    TaskUC ..> TaskCreateUC: "include"
    TaskUC ..> TaskEditUC: "include"
    TaskUC ..> TaskDeletetUC: "include"
    TaskUC ..> TaskRestoreUC: "include"
    TaskUC ..> TaskMoveUC: "include"

Admin -- СollaborationUC
    СollaborationUC ..> InviteUC: "include"
    СollaborationUC ..> RemoveUC: "include"
    СollaborationUC ..> UpdateUC: "include"
    СollaborationUC ..> UserCategoryUC: "include"


Admin -- ProjectUC
    ProjectUC ..> ProjectCreateUC: "include"
    ProjectUC ..> ProjectEditUC: "include"
    ProjectUC ..> ProjectDeleteUC: "include"

Admin -- LogUC
Admin -- StatisticsUC
LogUC ..> SaveLogUC: "include"
}
@enduml
