@startuml CreateProject
actor Пользователь as User
participant "Веб-браузер" as Browser
participant "Контроллер проекта" as PC
participant "Сервис проекта и пользователя" as UPS
participant "База данных" as DB

User -> Browser: Запросить страницу создания проекта
Browser -> PC: GET /Projects/CreateProject
PC -> Browser: Вернуть страницу создания проекта

User -> Browser: Заполнить форму и отправить данные проекта
Browser -> PC: POST /Projects/CreateProject с данными проекта

PC -> UPS: Получить текущего пользователя
UPS -> DB: Выполнить запрос для получения пользователя
DB --> UPS: Возвращаем текущего пользователя
UPS --> PC: Возвращаем текущего пользователя

alt Текущий пользователь найден
    PC -> DB: Создать новый проект
    DB --> PC: Подтверждение создания проекта

    PC -> DB: Создать связь с новым проектом для текущего пользователя
    DB --> PC: Подтверждение создания записи

    PC -> DB: Создать статусы проекта (В процессе, На проверке, Отложенные, Завершенные)
    DB --> PC: Подтверждение создания статусов

    PC -> DB: Создать приоритеты проекта (Низкий, Средний, Высокий)
    DB --> PC: Подтверждение создания приоритетов

    PC -> DB: Сохранить изменения
    DB --> PC: Подтверждение сохранения

    PC -> Browser: Перенаправить на страницу всех проектов
else Текущий пользователь не найден
    PC -> Browser: Перенаправить на страницу входа
end
@enduml