@startuml DeleteIssue
actor Пользователь as User
participant "Веб-браузер" as Browser
participant "Контроллер проекта" as PC
participant "Сервис проекта и пользователя" as UPS
participant "База данных" as DB

User -> Browser: Перейти на страницу проекта
Browser -> PC: GET /Projects/Project/{projectID}
PC -> UPS: Получить текущего пользователя
UPS -> DB: Выполнить запрос для получения пользователя
DB --> UPS: Возвращаем текущего пользователя
UPS --> PC: Возвращаем текущего пользователя

PC -> UPS: Получить проект по ID
UPS -> DB: Выполнить запрос для получения проекта
DB --> UPS: Возвращаем проект
UPS --> PC: Возвращаем проект

alt Проект и пользователь найдены
    PC -> Browser: Вернуть страницу проекта с задачами

    User -> Browser: Выбрать задачу для удаления и отправить форму
    Browser -> PC: POST /Projects/DeleteIssue с issueID

    PC -> UPS: Получить текущего пользователя
    UPS -> DB: Выполнить запрос для получения пользователя
    DB --> UPS: Возвращаем текущего пользователя
    UPS --> PC: Возвращаем текущего пользователя

    PC -> UPS: Получить проект по ID
    UPS -> DB: Выполнить запрос для получения проекта
    DB --> UPS: Возвращаем проект
    UPS --> PC: Возвращаем проект

    PC -> DB: Получить задачу по ID
    DB --> PC: Возвращаем задачу

    alt Задача найдена
        PC -> DB: Проверить, имеет ли пользователь права на удаление задачи
        DB --> PC: Возвращаем результат проверки


        PC -> DB: Удалить задачу (установить статус удаления и дату удаления)
        DB --> PC: Подтверждение удаления задачи

        PC -> DB: Добавить запись в лог
        DB --> PC: Подтверждение добавления записи в лог

        PC -> DB: Сохранить изменения
        DB --> PC: Подтверждение сохранения

        PC -> Browser: Перенаправить на страницу проекта
        
    else Задача не найдена
        PC -> Browser: Перенаправить на страницу ошибки (задача не найдена)
    end
else Проект или пользователь не найдены
    PC -> Browser: Перенаправить на страницу ошибки
end
@enduml