@startuml RemoveUser
actor Пользователь as User
participant "Веб-браузер" as Browser
participant "Контроллер проекта" as PC
participant "Сервис проекта и пользователя" as UPS
participant "База данных" as DB

User -> Browser: Перейти на страницу настроек проекта
Browser -> PC: GET /Projects/ProjectSettings/{projectID}
PC -> UPS: Получить текущего пользователя
UPS -> DB: Выполнить запрос для получения пользователя
DB --> UPS: Возвращаем текущего пользователя
UPS --> PC: Возвращаем текущего пользователя

PC -> UPS: Получить проект по ID
UPS -> DB: Выполнить запрос для получения проекта
DB --> UPS: Возвращаем проект
UPS --> PC: Возвращаем проект

alt Проект и пользователь найдены
    PC -> UPS: Получить список пользователей проекта
    UPS -> DB: Выполнить запрос для получения пользователей проекта
    DB --> UPS: Возвращаем список пользователей проекта
    UPS --> PC: Возвращаем список пользователей проекта

    PC -> Browser: Вернуть страницу настроек проекта с списком пользователей

    User -> Browser: Выбрать пользователя для удаления и отправить форму
    Browser -> PC: POST /Projects/RemoveUserFromProject с userProjectID

    PC -> UPS: Получить текущего пользователя
    UPS -> DB: Выполнить запрос для получения пользователя
    DB --> UPS: Возвращаем текущего пользователя
    UPS --> PC: Возвращаем текущего пользователя

    PC -> UPS: Получить проект по ID
    UPS -> DB: Выполнить запрос для получения проекта
    DB --> UPS: Возвращаем проект
    UPS --> PC: Возвращаем проект

    PC -> UPS: Получить связь пользователя с проектом по ID
    UPS -> DB: Выполнить запрос для получения связи
    DB --> UPS: Возвращаем связь
    UPS --> PC: Возвращаем связь

    alt Связь пользователя с проектом найдена
        alt Пользователь имеет права на удаление
            PC -> DB: Удалить связи пользователя с проектом
            DB --> PC: Подтверждение удаления связи

            PC -> DB: Добавить запись в лог
            DB --> PC: Подтверждение добавления записи в лог

            PC -> DB: Сохранить изменения
            DB --> PC: Подтверждение сохранения

            PC -> Browser: Перенаправить на страницу настроек проекта
        else Пользователь не имеет прав на удаление
            PC -> Browser: Перенаправить на страницу ошибки
        end
    else Связь пользователя с проектом не найдена
        PC -> Browser: Перенаправить на страницу ошибки
    end
else Проект или пользователь не найдены
    PC -> Browser: Перенаправить на страницу ошибки
end
@enduml