@startuml EditIssue
actor Пользователь as User
participant "Веб-браузер" as Browser
participant "Контроллер проекта" as PC
participant "Сервис проекта и пользователя" as UPS
participant "База данных" as DB

User -> Browser: Запросить страницу редактирования задачи
Browser -> PC: GET /Projects/Project/{projectID}
PC -> UPS: Получить текущего пользователя
UPS -> DB: Выполнить запрос для получения пользователя
DB --> UPS: Возвращаем текущего пользователя
UPS --> PC: Возвращаем текущего пользователя

PC -> UPS: Получить проект по ID
UPS -> DB: Выполнить запрос для получения проекта
DB --> UPS: Возвращаем проект
UPS --> PC: Возвращаем проект

alt Проект и пользователь найдены
    PC -> UPS: Получить задачу по ID
    UPS -> DB: Выполнить запрос для получения задачи
    DB --> UPS: Возвращаем задачу
    UPS --> PC: Возвращаем задачу

    alt Задача найдена
        PC -> Browser: Вернуть страницу редактирования задачи с данными задачи

        User -> Browser: Заполнить форму и отправить обновленные данные задачи
        Browser -> PC: POST /Projects/UpdateIssueAsync с обновленными данными задачи

        PC -> UPS: Получить текущего пользователя
        UPS -> DB: Выполнить запрос для получения пользователя
        DB --> UPS: Возвращаем текущего пользователя
        UPS --> PC: Возвращаем текущего пользователя

        PC -> UPS: Получить проект по ID
        UPS -> DB: Выполнить запрос для получения проекта
        DB --> UPS: Возвращаем проект
        UPS --> PC: Возвращаем проект


        PC -> UPS: Получить задачу по ID
        UPS -> DB: Выполнить запрос для получения задачи
        DB --> UPS: Возвращаем задачу
        UPS --> PC: Возвращаем задачу

        PC -> DB: Обновить данные задачи
        DB --> PC: Подтверждение обновления задачи

        PC -> DB: Добавить запись в лог
        DB --> PC: Подтверждение добавления записи в лог

        PC -> DB: Сохранить изменения
        DB --> PC: Подтверждение сохранения

        PC -> Browser: Перенаправить на страницу проекта

    else Задача не найдена
        PC -> Browser: Перенаправить на страницу ошибки
    end
else Проект или пользователь не найдены
    PC -> Browser: Перенаправить на страницу ошибки
end
@enduml