@startuml LeaveProject
actor Пользователь as User
participant "Веб-браузер" as Browser
participant "Контроллер проекта" as PC
participant "Сервис проекта и пользователя" as UPS
participant "База данных" as DB
User -> Browser: Нажать кнопку "Выйти из проекта"
Browser -> PC: POST /Projects/LeaveProject с projectID

PC -> UPS: Получить текущего пользователя
UPS -> DB: Выполнить запрос для получения пользователя
DB --> UPS: Возвращаем текущего пользователя
UPS --> PC: Возвращаем текущего пользователя

PC -> UPS: Получить проект по ID
UPS -> DB: Выполнить запрос для получения проекта
DB --> UPS: Возвращаем проект
UPS --> PC: Возвращаем проект

PC -> DB: Получить связь между проектом и пользователем по UserID и ProjectID
DB --> PC: Возвращаем связь

alt Связь между проектом и пользователем найдена
    PC -> DB: Удалить связь между проектом и пользователем
    DB --> PC: Подтверждение удаления записи

    PC -> DB: Добавить запись в лог
    DB --> PC: Подтверждение добавления записи в лог

    PC -> DB: Сохранить изменения
    DB --> PC: Подтверждение сохранения

PC -> Browser: Перенаправить на страницу всех проектов
else Связь между проектом и пользоватeлем не найдена
    PC -> Browser: Перенаправить на страницу ошибки
end
@enduml