@startuml PasswordRecovery
actor Пользователь as User
participant "Веб-браузер" as Browser
participant "Контроллер пользователей" as UC
participant "Сервис электронной почты" as MS
participant "База данных" as DB

User -> Browser: Перейти на страницу восстановления пароля
Browser -> UC: GET /Users/PasswordRecoveryRequest
UC -> Browser: Вернуть страницу восстановления пароля

User -> Browser: Ввести email и отправить форму
Browser -> UC: POST /Users/PasswordRecoveryRequest с email

UC -> DB: Найти пользователя по email
DB --> UC: Возвращаем пользователя

alt Пользователь найден и активен
    UC -> DB: Генерировать токен восстановления пароля
    DB --> UC: Возвращаем токен восстановления пароля

    UC -> DB: Обновить токен восстановления пароля и дату
    DB --> UC: Подтверждение обновления токена и даты

    UC -> MS: Отправить письмо с ссылкой для восстановления пароля
    MS --> UC: Подтверждение отправки письма


    UC -> DB: Сохранить изменения
    DB --> UC: Подтверждение сохранения

    UC -> Browser: Перенаправить на страницу ожидания восстановления пароля
else Пользователь не найден или не активен
    UC -> Browser: Перенаправить на страницу ошибки восстановления пароля
end

User -> Browser: Перейти по ссылке из письма
Browser -> UC: GET /Users/PasswordRecovery с token

UC -> DB: Найти пользователя по токену восстановления пароля
DB --> UC: Возвращаем пользователя

alt Пользователь найден и токен действителен
    UC -> Browser: Вернуть страницу для ввода нового пароля
else Пользователь не найден или токен недействителен
    UC -> Browser: Перенаправить на страницу ошибки восстановления пароля
end

User -> Browser: Ввести новый пароль и повторить его
Browser -> UC: POST /Users/PasswordRecovery с token, HashPass и HashPassRepeat

UC -> DB: Найти пользователя по токену восстановления пароля
DB --> UC: Возвращаем пользователя

alt Пользователь найден и токен действителен
    UC -> DB: Проверить, совпадают ли новые пароли
    DB --> UC: Возвращаем результат проверки

    alt Пароли совпадают
        UC -> DB: Обновить хэш пароля пользователя
        DB --> UC: Подтверждение обновления хэша пароля

        UC -> DB: Очистить токен восстановления пароля и дату
        DB --> UC: Подтверждение очистки токена и даты

        UC -> DB: Сохранить изменения
        DB --> UC: Подтверждение сохранения

        UC -> Browser: Перенаправить на страницу сообщения об успешном восстановлении пароля
    else Пароли не совпадают
        UC -> Browser: Перенаправить на страницу ошибки восстановления пароля
    end
else Пользователь не найден или токен недействителен
    UC -> Browser: Перенаправить на страницу ошибки восстановления пароля
end
@enduml