@startuml SaveProjectLog
actor Пользователь as User
participant "Веб-браузер" as Browser
participant "Контроллер проекта" as PC
participant "Сервис проекта и пользователя" as UPS
participant "Сервис создания отчетов" as ERS
participant "База данных" as DB

User -> Browser: Открыть страницу истории проекта
Browser -> PC: GET /Projects/ProjectHistory/{projectID}
PC -> UPS: Получить текущего пользователя
UPS -> DB: Выполнить запрос для получения пользователя
DB --> UPS: Возвращаем текущего пользователя
UPS --> PC: Возвращаем текущего пользователя

PC -> UPS: Получить проект по ID
UPS -> DB: Выполнить запрос для получения проекта
DB --> UPS: Возвращаем проект
UPS --> PC: Возвращаем проект

alt Проект и пользователь найдены
    PC -> DB: Получить лог проекта
    DB --> PC: Возвращаем лог проекта

    PC -> Browser: Вернуть страницу истории проекта с логом

    User -> Browser: Нажать кнопку "Скачать историю"
    Browser -> PC: GET /Projects/DownloadHistory/{projectID}

    PC -> UPS: Получить текущего пользователя
    UPS -> DB: Выполнить запрос для получения пользователя
    DB --> UPS: Возвращаем текущего пользователя
    UPS --> PC: Возвращаем текущего пользователя

    PC -> UPS: Получить проект по ID
    UPS -> DB: Выполнить запрос для получения проекта
    DB --> UPS: Возвращаем проект
    UPS --> PC: Возвращаем проект


    PC -> DB: Получить лог проекта
    DB --> PC: Возвращаем лог проекта

    PC -> ERS: Создать Excel-отчет из лога проекта
    ERS --> PC: Возвращаем Excel-отчет

    PC -> Browser: Отправить Excel-отчет для скачивания

else Проект или пользователь не найдены
    PC -> Browser: Перенаправить на страницу ошибки
end
@enduml